### ISSUE TITLE
[Server] Crash (java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen)

### ISSUE THREAD

**Issue by aking4125** [Artiks54/Torcherino-ce#1]
Hello, upon adding this to the server. The server crashes with the following report.

[crash-2024-02-03_03.43.28-server.txt](https://github.com/Artiks54/Torcherino-ce/files/14150867/crash-2024-02-03_03.43.28-server.txt)
[debug.log](https://github.com/Artiks54/Torcherino-ce/files/14150870/debug.log)

Works on the client, server boots without this mod installed. Any ideas?

**Comment by Artiks54** [comment]
Hello, I am aware of this problem and it has already been solved.
A new update will be released soon.
